import { Article } from "@/types/type";

export const articlesData: Article[] = [
  {
    id: 1,
    title: "التحولات في أدب فرانز كافكا: بحث في الاغتراب",
    excerpt:
      "دراسة تحليلية للبعد الرمزي في رواية المسخ وكيف أثرت على الأدب الوجودي الحديث عبر الأجيال.",
    image: "/images/heroImage.svg",
    category: "نقد كلاسيكي",
    author: "أحمد إبراهيم",
    publishedAt: "١٥ مايو ٢٠٢٦",
    slug: "franz-kafka",
  },
  {
    id: 2,
    title: "تولستوي والزمن في الحرب والسلام",
    excerpt: "كيف جعل تولستوي الزمن شخصية روائية تتحكم في مصائر أبطاله.",
    image: "/images/heroImage.svg",
    category: "روايات",
    author: "محمد خالد",
    publishedAt: "٢١ مايو ٢٠٢٦",
    slug: "war-and-peace",
  },
  {
    id: 3,
    title: "نجيب محفوظ بين الواقعية والرمزية",
    excerpt: "قراءة جديدة في الثلاثية وتأثيرها على الرواية العربية الحديثة.",
    image: "/images/heroImage.svg",
    category: "الأدب العربي",
    author: "سارة علي",
    publishedAt: "٢٧ مايو ٢٠٢٦",
    slug: "naguib-mahfouz",
  },
  {
    id: 4,
    title: "دوستويفسكي وصراع النفس البشرية",
    excerpt: "تحليل لأهم الشخصيات الروائية في الجريمة والعقاب.",
    image: "/images/heroImage.svg",
    category: "تحليل أدبي",
    author: "عمر حسن",
    publishedAt: "٣ يونيو ٢٠٢٦",
    slug: "crime-and-punishment",
  },
  {
    id: 5,
    title: "الرمزية في شعر محمود درويش",
    excerpt: "كيف استطاع درويش بناء صور شعرية خالدة عبر الرموز.",
    image: "/images/heroImage.svg",
    category: "الشعر",
    author: "إيمان يوسف",
    publishedAt: "١٠ يونيو ٢٠٢٦",
    slug: "mahmoud-darwish",
  },
  {
    id: 6,
    title: "الرمزية في شعر محمود درويش",
    excerpt: "كيف استطاع درويش بناء صور شعرية خالدة عبر الرموز.",
    image: "/images/heroImage.svg",
    category: "الشعر",
    author: "إيمان يوسف",
    publishedAt: "١٠ يونيو ٢٠٢٦",
    slug: "mahmoud-darwish",
  },
];
